name: Playwright Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    #runs-on: self-hosted ## Uncomment this line to run on a self-hosted runner
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup node js
        uses: actions/setup-node@v4
        with:
            node-version: '20'
            cache: 'npm'

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'adopt'

      - name: Install maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
            checkout-fetch-depth: 0
            java-version: '17'
            java-distribution: 'adopt'
            maven-version: '3.9.9'

      - name: Install npm playwright dependencies
        run: npx playwright install-deps

      - name: Cache maven dependencies
        uses: actions/cache@v4
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
              ${{ runner.os }}-maven

      - name: Run tests
        run: mvn verify

      - name: Archive tracing results
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: trace-results
            path: target/traces/*.zip

      - name: Deploy allure reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: target/site/allure-maven-plugin